version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - my-network

  node:
    build:
      context: ./node
      platforms: ['linux/amd64']
    volumes:
      - ./node:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 10s
      retries: 4

networks:
  my-network:
    driver: bridge

volumes:
  mysql:
    driver: local
